name: Update iota.rb info
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # update at every day 20:00(utc+8)

jobs:
  update-iota-rb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get package.json
        run: |
          curl -s -A "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0" -H "Accept: application/json" "https://https://iotademo.gss.com.tw/download/package.json" --resolve https://iotademo.gss.com.tw:443:175.99.166.66 -O

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .app.mac.version package.json -r"

      - name: Extract download path from package.json
        uses: sergeysova/jq-action@v2
        id: downloadPath
        with:
          cmd: "jq .app.mac.url package.json -r"

      - name: Download iota.dmg
        run: |
          curl -A "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0" "https://https://iotademo.gss.com.tw/download/iota.dmg" --resolve https://iotademo.gss.com.tw:443:175.99.166.66 -O
          echo "checksum=$(shasum -a 256 iota.dmg | awk '{ print $1 }')" >> $GITHUB_ENV

      - name: Build iota.rb
        run: |
          cat << EOF > ./Casks/iota.rb 
          cask "iota" do
            version "${{ steps.version.outputs.value }}"
            sha256 "${{ env.checksum }}"

            url "https://https://iotademo.gss.com.tw/download/iota.dmg",
                user_agent: :fake
            name "iota"
            homepage "https://https://iotademo.gss.com.tw/"

            app "iota.app"
          end
          EOF

      - name: Commit files
        id: commit
        continue-on-error: true
        run: |
          git config --local user.email "a26007565@gmail.com"
          git config --local user.name "weiting"
          git commit -m "chore: Update iota.rb" -a

      - name: Push changes
        if: steps.commit.outcome == 'success' && steps.commit.conclusion == 'success'
        uses: ad-m/github-push-action@master
        with:
          branch: master
